### PR TITLE
Soundsensers linux

### PR DESCRIPTION
**Pull request by DHMike57**
Fix for the linux webkit problem of 'can't find variable external' resulting in ui unresponsive to mouse clicks.
See  [issue](https://github.com/prixt/soundsense-rs/issues/19) at soundsense-rs repository.  Needs rust compiler to rebuild from source.

### CODE REVIEW

**Comment by McArcady** [comment]
Good idea! Soundsense-RS seems unmaintained, so it's a good thing if we provide major patches through lnp-forge.

BTW, would you know how to solve this build error (I'm not familiar with cargo and rust):
`error: the lock file /home/francois/workspace/df/lnp-forge/.build/src/soundsense-rs-v1.5.1/Cargo.lock needs to be updated but --locked was passed to prevent this
`

**Comment by DHMike57** [comment]
> BTW, would you know how to solve this build error (I'm not familiar with cargo and rust):
> `error: the lock file .build/src/soundsense-rs-v1.5.1/Cargo.lock needs to be updated but --locked was passed to prevent this `

Sorry, I don't know much about it either - it just built for me!  One thing I notice: I had the version in .config set to 'master' when it worked for me, and I did quite a few runs from scratch.  Unfortunately the prix repository has 350MB of deleted soundpack in the history which makes cloning it a PITA.  I made a cleaned-up version, but it broke the fork connection.

Finally, sorry about the two-part PR: I'm not very experienced at this!

Mike

**Comment by Podesta** [comment]
> Unfortunately the prix repository has 350MB of deleted soundpack in the history which makes cloning it a PITA. I made a cleaned-up version, but it broke the fork connection.

You can always clone with `--depth=1`. But yeah, the optimal would be changing the history, and removing the offending files/commits, but I'm not sure if that would also break fork connection.

**Comment by McArcady** [comment]
Thanks again for the patch but I cannot get it to build on my Debian. Too many unsolvable missing dependencies...
Let's hope someone takes up the maintenance of Soundsense-RS.

**Comment by DHMike57** [comment]
> > Unfortunately the prix repository has 350MB of deleted soundpack in the history which makes cloning it a PITA. I made a cleaned-up version, but it broke the fork connection.
> 
> You can always clone with `--depth=1`. But yeah, the optimal would be changing the history, and removing the offending files/commits, but I'm not sure if that would also break fork connection.

Good solution (to this very superficial git user anyway!). 'Breaks the fork connection' was ill chosen: the connection remains, but the PR was unusable because of the huge number of history changes that it incorporated.  Perhaps there is a way to get around this with a deeper understanding of the innards of git.

**Comment by DHMike57** [comment]
I think I have a fix for the build failure: web-view is updated to v0.7 in Cargo.toml , and you must compile without the --locked flag.  It compiles for me on arch, but I also got it to compile on the github ubuntu-latest, where the original version with v0.6 failed.

**Comment by DHMike57** [comment]
After a crash course in github workflows I think this is finally working: the build workflow completes without errors in my fork branch.  The missing dependencies are 
```
- libasound2-dev  
- libgtk-3-dev 
- libwebkit2gtk-4.0-dev
```
in ubuntu and hopefully in other debian systems.  Fingers crossed!

**Pull request merged**
